package io.github.pyvesb.alexarevolutionarycalendar.date;

public enum FrenchObjectOfTheDay {

	Raisin("le "),
	Safran("le "),
	Châtaigne("la "),
	Colchique("le "),
	Cheval("le "),
	Balsamine("la "),
	Carotte("la "),
	Amaranthe("l'"),
	Panais("le "),
	Cuve("la "),
	Pomme_de_terre("la "),
	Immortelle("l'"),
	Potiron("le "),
	Réséda("le "),
	Âne("l'"),
	Belle_de_nuit("la "),
	Citrouille("la "),
	Sarrasin("le "),
	Tournesol("le "),
	Pressoir("le "),
	Chanvre("le "),
	Pêche("la "),
	Navet("le "),
	Amaryllis("l'"),
	Bœuf("le "),
	Aubergine("l'"),
	Piment("le "),
	Tomate("la "),
	Orge("l'"),
	Tonneau("le "),
	Pomme("la "),
	Céleri("le "),
	Poire("la "),
	Betterave("la "),
	Oie("l'"),
	Héliotrope("l'"),
	Figue("la "),
	Scorsonère("la "),
	Alisier("l'"),
	Charrue("la "),
	Salsifis("le "),
	Mâcre("la "),
	Topinambour("le "),
	Endive("l'"),
	Dindon("le "),
	Chervis("le "),
	Cresson("le "),
	Dentelaire("la "),
	Grenade("la "),
	Herse("la "),
	Bacchante("la "),
	Azerole("l'"),
	Garance("la "),
	Orange("l'"),
	Faisan("le "),
	Pistache("la"),
	Macjonc("le "),
	Coing("le "),
	Cormier("le "),
	Rouleau("le "),
	Raiponce("la "),
	Turneps("le "),
	Chicorée("la "),
	Nèfle("la "),
	Cochon("le "),
	Mâche("la "),
	Chou_fleur("le "),
	Miel("le "),
	Genièvre("le "),
	Pioche("la "),
	Cire("la "),
	Raifort("le "),
	Cèdre("le "),
	Sapin("le "),
	Chevreuil("le "),
	Ajonc("l'"),
	Cyprès("le "),
	Lierre("le "),
	Sabine("la "),
	Hoyau("le "),
	Érable_à_sucre("l'"),
	Bruyère("la "),
	Roseau("le "),
	Oseille("l'"),
	Grillon("le "),
	Pignon("le "),
	Liège("le "),
	Truffe("la "),
	Olive("l'"),
	Pelle("la "),
	Tourbe("la "),
	Houille("la "),
	Bitume("le "),
	Soufre("le "),
	Chien("le "),
	Lave("la "),
	Terre_végétale("la "),
	Fumier("le "),
	Salpêtre("le "),
	Fléau("le "),
	Granit("le "),
	Argile("l'"),
	Ardoise("l'"),
	Grès("le "),
	Lapin("le "),
	Silex("le "),
	Marne("la "),
	Pierre_à_chaux("la "),
	Marbre("le "),
	Van("le "),
	Pierre_à_plâtre("la "),
	Sel("le "),
	Fer("le "),
	Cuivre("le "),
	Chat("le "),
	Étain("l'"),
	Plomb("le "),
	Zinc("le "),
	Mercure("le "),
	Crible("le "),
	Lauréole("le "),
	Mousse("la "),
	Fragon("le "),
	Perce_neige("le "),
	Taureau("le "),
	Laurier_thym("le "),
	Amadouvier("l'"),
	Mézéréon("le "),
	Peuplier("le "),
	Coignée("la "),
	Ellébore("l'"),
	Brocoli("le "),
	Laurier("le "),
	Avelinier("l'"),
	Vache("la "),
	Buis("le "),
	Lichen("le "),
	If("l'"),
	Pulmonaire("le "),
	Serpette("la "),
	Thlaspi("le "),
	Thimelé("le "),
	Chiendent("le "),
	Trainasse("la "),
	Lièvre("le "),
	Guède("la "),
	Noisetier("le "),
	Cyclamen("le "),
	Chélidoine("la "),
	Traîneau("le "),
	Tussilage("le "),
	Cornouiller("le "),
	Violier("le "),
	Troène("le "),
	Bouc("le "),
	Asaret("l'"),
	Alaterne("l'"),
	Violette("la "),
	Marceau("le "),
	Bêche("la "),
	Narcisse("le "),
	Orme("l'"),
	Fumeterre("la "),
	Vélar("le "),
	Chèvre("la "),
	Épinard("l'"),
	Doronic("le "),
	Mouron("le "),
	Cerfeuil("le "),
	Cordeau("le "),
	Mandragore("la "),
	Persil("le "),
	Cochléaria("le "),
	Pâquerette("la "),
	Thon("le "),
	Pissenlit("le "),
	Sylvie("la "),
	Capillaire("le "),
	Frêne("le "),
	Plantoir("le "),
	Primevère("le "),
	Platane("le "),
	Asperge("l'"),
	Tulipe("la "),
	Poule("la "),
	Bette("la "),
	Bouleau("le "),
	Jonquille("la "),
	Aulne("l'"),
	Couvoir("le "),
	Pervenche("la "),
	Charme("le "),
	Morille("la "),
	Hêtre("le "),
	Abeille("l'"),
	Laitue("la "),
	Mélèze("le "),
	Ciguë("la "),
	Radis("le "),
	Ruche("la "),
	Gainier("le "),
	Romaine("la "),
	Marronnier("le "),
	Roquette("la "),
	Pigeon("le "),
	Lilas("le "),
	Anémone("l'"),
	Pensée("la "),
	Myrtille("la "),
	Greffoir("le "),
	Rose("la "),
	Chêne("le "),
	Fougère("la "),
	Aubépine("l'"),
	Rossignol("le "),
	Ancolie("l'"),
	Muguet("le "),
	Champignon("le "),
	Hyacinthe("la "),
	Râteau("le "),
	Rhubarbe("la "),
	Sainfoin("le "),
	Bâton_d_or("le "),
	Chamerisier("le "),
	Ver_à_soie("le "),
	Consoude("la "),
	Pimprenelle("la "),
	Corbeille_d_or("la "),
	Arroche("l'"),
	Sarcloir("le "),
	Statice("le "),
	Fritillaire("la "),
	Bourrache("la "),
	Valériane("la "),
	Carpe("la "),
	Fusain("le "),
	Civette("la "),
	Buglosse("la "),
	Sénevé("le "),
	Houlette("la "),
	Luzerne("la "),
	Hémérocalle("l'"),
	Trèfle("le "),
	Angélique("l'"),
	Canard("le "),
	Mélisse("la "),
	Fromental("le "),
	Martagon("le "),
	Serpolet("le "),
	Faux("la "),
	Fraise("la "),
	Bétoine("la "),
	Pois("le "),
	Acacia("l'"),
	Caille("la "),
	Œillet("l'"),
	Sureau("le "),
	Pavot("le "),
	Tilleul("le "),
	Fourche("la "),
	Barbeau("le "),
	Camomille("la "),
	Chèvrefeuille("le "),
	Caille_lait("la "),
	Tanche("la "),
	Jasmin("le "),
	Verveine("la "),
	Thym("le "),
	Pivoine("la "),
	Chariot("le "),
	Seigle("le "),
	Avoine("l'"),
	Oignon("l'"),
	Véronique("la "),
	Mulet("le "),
	Romarin("le "),
	Concombre("le "),
	Échalote("l'"),
	Absinthe("l'"),
	Faucille("la "),
	Coriandre("le "),
	Artichaut("l'"),
	Girofle("le "),
	Lavande("la "),
	Chamois("le "),
	Tabac("le "),
	Groseille("la "),
	Gesse("la "),
	Cerise("la "),
	Parc("le "),
	Menthe("la "),
	Cumin("le "),
	Haricot("le "),
	Orcanète("l'"),
	Pintade("la "),
	Sauge("la "),
	Ail("l'"),
	Vesce("la "),
	Blé("le "),
	Chalémie("la "),
	Épeautre("l'"),
	Bouillon_blanc("le "),
	Melon("le "),
	Ivraie("l'"),
	Bélier("le "),
	Prêle("la "),
	Armoise("l'"),
	Carthame("le "),
	Mûre("la "),
	Arrosoir("l'"),
	Panic("le "),
	Salicorne("la "),
	Abricot("l'"),
	Basilic("le "),
	Brebis("la "),
	Guimauve("la "),
	Lin("le "),
	Amande("l'"),
	Gentiane("la "),
	Écluse("l'"),
	Carline("la "),
	Câprier("le "),
	Lentille("la "),
	Aunée("l'"),
	Loutre("la "),
	Myrte("le "),
	Colza("le "),
	Lupin("le "),
	Coton("le "),
	Moulin("le "),
	Prune("la "),
	Millet("le "),
	Lycoperdon("le "),
	Escourgeon("l'"),
	Saumon("le "),
	Tubéreuse("la "),
	Sucrion("le "),
	Apocyn("l'"),
	Réglisse("la "),
	Échelle("l'"),
	Pastèque("la "),
	Fenouil("le "),
	Épine_vinette("l'"),
	Noix("la "),
	Truite("la "),
	Citron("le "),
	Cardère("la "),
	Nerprun("le "),
	Tagette("le "),
	Hotte("la "),
	Églantier("l'"),
	Noisette("la "),
	Houblon("le "),
	Sorgho("le "),
	Écrevisse("l'"),
	Bigarade("la "),
	Verge_d_or("la "),
	Maïs("le "),
	Marron("le "),
	Panier("le "),
	Vertu("la "),
	Génie("le "),
	Travail("le "),
	Opinion("l'"),
	Récompenses("les "),
	Révolution("la ");

	private final String article;

	private FrenchObjectOfTheDay(String article) {
		this.article = article;
	}

	public String getArticle() {
		return article;
	}

}
